### ISSUE TITLE
 reconnect server

### ISSUE THREAD

**Issue by xianghu1314** [nats-io/stan.net#134]
@ColinSullivan1 
i have a question.  i try to reconnect server when the connect lost . but the server respense error "the clientid already exists"，this is my code:
```csharp
        public void NatsListen(Config config, Func<HttpRepData, bool> func)
        {
            IStanConnection c = null;
            try
            {
                var cf = new StanConnectionFactory();
                var opts = StanOptions.GetDefaultOptions();
                opts.NatsURL = config.NatsUrl;
                opts.PingInterval = 5000;
                opts.PingMaxOutstanding = 5;
                opts.ConnectionLostEventHandler = (obj, args) =>
                {
                    // handle the case where a connection has been lost
                   
                    Thread.Sleep(1000);
                   
                    if (c != null)
                    {
                        c.Close();
                    }
                    NatsListen(config, func);
                };
                //test-cluster
                var clientId = "Gate-Brake-Offline-Order-client-" + SerialNumber;
                
                c = cf.CreateConnection(config.NatsClusterID, clientId, opts);
                // Subscribe with a durable name
                var opts1 = StanSubscriptionOptions.GetDefaultOptions();
                opts1.DurableName = "gate-brake-offline-order-durable";
                //opts1.DeliverAllAvailable();
                var s = c.Subscribe("GateBrake-AddCard", opts1, (obj, data) =>
                {

                    var str = System.Text.Encoding.UTF8.GetString(data.Message.Data);
                   
                    var res = JsonConvert.DeserializeObject<HttpRepData>(str);
                    func(res);
                    //Console.WriteLine("Received a message: {0}",System.Text.Encoding.UTF8.GetString(data.Message.Data));
                });
                var s2 = c.Subscribe("GateBrake-DelCard", opts1, (obj, data) =>
                {

                    var str = System.Text.Encoding.UTF8.GetString(data.Message.Data);
                    
                    var res = JsonConvert.DeserializeObject<HttpRepData>(str);
                    func(res);
                    //Console.WriteLine("Received a message: {0}",System.Text.Encoding.UTF8.GetString(data.Message.Data));
                });
            }
            catch (Exception e)
            {
                
                Thread.Sleep(1000);
                if (c != null)
                {
                    c.Close();
                }
                NatsListen(config, func);
            }
        }
```

**Comment by xianghu1314** [comment]
@wallyqs @derekcollison @jeppevammenkristensen @DaleBingham

**Comment by derekcollison** [comment]
Ping for @ColinSullivan1

**Comment by ColinSullivan1** [comment]
@xianghu1314 , thank you for reporting this.  Which version of the NATS streaming server and STAN.Client you are using?

**Comment by xianghu1314** [comment]
> @xianghu1314 , thank you for reporting this. Which version of the NATS streaming server and STAN.Client you are using?

The NATS streaming server`s version is 0.16.0 of docker image [docker image](https://docs.docker.com/samples/library/nats-streaming/). and the STAN.Client Version is  "<package id="NATS.Client" version="0.8.1" targetFramework="net45" />". In the development  environment When i close the network  it looks work good as expected . but in the production environment i got the errors(i can`t get the network condition ).  I am glad to receive your reply.

**Comment by ColinSullivan1** [comment]
@xianghu1314,

Looking at your code closer, I'd suggest attempting connections in a loop rather than recursing.  There are a few reasons for this:
* If the server is down long enough, you'll run out of stack space
* As you recurse down through errors, you could have have orphaned connection and subscription objects (at least for period of time) with active subscriptions/connections on the NATS streaming server.

I think the problem may be that you are getting an exception, recursing down into recreating the connection while at the same time having the disconnected handler fired (creating a new connection) resulting the the duplicate client ID.  Either you'll want to add some locking to prevent this condition, or remove the recursion.  Differences in timing between environments would explain why you'd see it production but not in your development environment.

My advice would be to run the listen code in a loop here until you are finished, and call the NatsListen function as a task from elsewhere.  Rather than closing the connection inside the ConnectLostEventHandler, you could trigger an AutoResetEvent the function waits on.

```text
// pseudocode
while (active)
{
   Create connection
   Create subscriptions
   wait until triggered to stop, or connection lost handler is invoked.  Maybe an auto reset event.
   cleanup subscriptions and connections
}
```

Your disconnected event handler could set the `AutoResetEvent` you are waiting on, and something external to the method would disable active and trigger the `AutoResetEvent` to break out of listening.

An example of using an `AutoResetEvent` to wait on subscribers (or in your case other conditions) can be found [here](https://github.com/nats-io/stan.net/blob/master/examples/stan-sub/stan-sub.cs#L78).

I hope this helps... Does this make sense?
