### ISSUE TITLE
issue out of memory: cannot allocate 122880-byte block (1756626944 in use)

### ISSUE THREAD

**Issue by minhhungit** [nats-io/stan.net#169]
- Windows
-  [nats-streaming-server-v0.16.2-windows-386](https://github.com/nats-io/nats-streaming-server/releases/download/v0.16.2/nats-streaming-server-v0.16.2-windows-386.zip)

When I publish about 10.000 messages to nats stream server I get out of memory issue while RAM is still available 

1 message ~ 100.000 bytes

![image](https://user-images.githubusercontent.com/2279508/71648554-64284280-2d38-11ea-8b02-61409d137b3e.png)

I also attached reproduce video and code for StanPub 

[StanPub.zip](https://github.com/nats-io/stan.net/files/4014716/demo.StanPub.zip)
[nats-stream-out-of-memory.zip](https://github.com/nats-io/stan.net/files/4014717/nats-stream-out-of-memory.zip)

---

Full exception detail:

[exception detail.txt](https://github.com/nats-io/stan.net/files/4014749/exception.detail.txt)

**Comment by minhhungit** [comment]
But it's good with docker image, here is video when I publish with docker

[nats-stream-ok-with-docker-image.zip](https://github.com/nats-io/stan.net/files/4014743/nats-stream-ok-with-docker-image.zip)

**Comment by minhhungit** [comment]
nats-streaming-server-v0.16.2-windows-amd64.zip work quite well

nats-streaming-server-v0.16.2-windows-386.zip does not

**Comment by ColinSullivan1** [comment]
This error seems reasonable.  On windows, without special switches and being compiled to be "large address space aware", a 32 bit process can only access a maximum of 2 GB of user space memory.

You're approaching that with 1.75 GB allocated, and I suspect at that point the heap manager can't find any pages available that satisfy the 122880 byte allocation request.

The size of your payloads are 1GB, and there is additional overhead the server uses to manage that.
 
There are flags so that the streaming server can access more memory, but if you have access to a 64 bit OS, we highly recommend you run the 64 bit streaming server.  Along with more user space memory (4GB) you'll see better performance.  CC @kozlovic

**Comment by kozlovic** [comment]
@ColinSullivan1 Nothing to add to what you have mentioned. The 32bit will indeed be limited in addressable memory space, so using the MEMORY store is then not the right choice. The user can try with file store or simply move to the 64bit version.

**Comment by minhhungit** [comment]
Yeah, thank you for your explain guys. I understood.
I will use 64bit version.
